CREATE TABLE IF NOT EXISTS users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, pin VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL, mobile VARCHAR(20) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL,
 role VARCHAR(12) NOT NULL, status VARCHAR(12) NOT NULL, department VARCHAR(100) NOT NULL,
 mentor_id BIGINT, review_note VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (mentor_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS leaves (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, kind VARCHAR(30) NOT NULL,
 start_date DATE NOT NULL, end_date DATE NOT NULL, reason VARCHAR(2000) NOT NULL,
 status VARCHAR(25) NOT NULL, recommendation VARCHAR(30) NOT NULL, analysis VARCHAR(1000) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS leave_events (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, leave_id BIGINT NOT NULL, actor_id BIGINT NOT NULL,
 action VARCHAR(30) NOT NULL, note VARCHAR(500) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (leave_id) REFERENCES leaves(id), FOREIGN KEY (actor_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS attendance (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, student_id BIGINT NOT NULL, attendance_date DATE NOT NULL,
 status VARCHAR(12) NOT NULL, marked_by BIGINT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (student_id,attendance_date), FOREIGN KEY (student_id) REFERENCES users(id), FOREIGN KEY (marked_by) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, message VARCHAR(1000) NOT NULL,
 is_read BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS reset_codes (
 user_id BIGINT PRIMARY KEY, code_hash VARCHAR(100) NOT NULL, expires_at TIMESTAMP NOT NULL,
 attempts INT DEFAULT 0, FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS sms_outbox (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, message VARCHAR(1200) NOT NULL,
 status VARCHAR(15) DEFAULT 'QUEUED', attempts INT DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id)
);
